apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.13.0-rc.2-management
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 5672
        - containerPort: 15672
        env: 
          - name: SEED_USERNAME
            valueFrom:
              secretKeyRef:
                key: SEED_USERNAME
                name: rabbitmq-secret
          - name: SEED_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                key: SEED_USER_PASSWORD
                name: rabbitmq-secret
        volumeMounts:
        - name: rabbitmq-broker
          mountPath: /var/lib/rabbitmq
      volumes:  
      - name: rabbitmq-broker
        persistentVolumeClaim:
          claimName: rabbitmq-pvc
